name: First Workflow
# manual trigger
on: workflow_dispatch
jobs:
  first-job:
#      define the env
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hello world"
      - name: print goodbye
        run: echo "done, bye"
  
